### ISSUE TITLE
Adding 2 contracts

### ISSUE THREAD

**Issue by inemp** [Pacoca-io/contracts#1]
Hello could you also add the 2 following contracts?

Macaron Swap: 0x0608A42BA74F2026A88aC2304f6802838F36bEB5
Kalata: 0x565bCba3eA730ac6987edE126B29DCf499fccEA1  I am not sure

**Comment by MrPeanutz** [comment]
What do you mean? Add to what?

**Comment by inemp** [comment]
hello, I mean that the two aforementioned smart contracts are not detected and thus do not appear in the dashboard. As for example apeswap baby swap and lots more do. Is it more clear now?

**Comment by MrPeanutz** [comment]
Integration requests should be made through https://feedback.pacoca.io
